IB_EXCHANGE_TO_CURRENCY = {
    "AEB": "EUR",
    "ARCA": "USD",
    "ASX": "AUD",
    "BATS": "USD",
    "BM": "EUR",
    "BVME": "EUR",
    "BVME.ETF": "EUR",
    "EBS": "CHF",
    "ENEXT.BE": "EUR",
    "FWB": "EUR",
    "FWB2": "EUR",
    "GETTEX": "EUR",
    "GETTEX2": "EUR",
    "IBIS": "EUR",
    "IBIS2": "EUR",
    "LSEETF": "EUR",
    "NASDAQ": "USD",
    "NYSE": "USD",
    "PINK": "USD",
    "PURE": "CAD",
    "SBF": "EUR",
    "SEHK": "HKD",
    "SGX": "SGD",
    "SWB": "EUR",
    "SWB2": "EUR",
    "TSE": "CAD",
    "VENTURE": "CAD",
    "VALUE": "EUR",
    "VSE": "EUR",
}

YAHOO_EXCHANGE_TO_CURRENCY = {
    "ASX": "AUD",
    "BTS": "USD",
    "CPH": "DKK",
    "EBS": "CHF",
    "FRA": "EUR",
    "GER": "EUR",
    "HKG": "HKD",
    "LSE": "GDP",
    "MCE": "EUR",
    "MIL": "EUR",
    "NCM": "USD",
    "NMS": "USD",
    "NYQ": "USD",
    "OSL": "NOK",
    "PAR": "EUR",
    "PCX": "USD",
    "PNK": "USD",
    "SES": "SGD",
    "STU": "EUR",
    "TOR": "CAD",
    "VIE": "EUR",
}

KNOWN_CURRENCIES = set(YAHOO_EXCHANGE_TO_CURRENCY.values()).union({"JPY"})
